version: "3"

# Statement, a network of networks, subnet configures subnet addresses for the network, the default gateway is 177.7.0.1
networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: '177.7.0.0/16'

# Set up the mysql, redis persisted
volumes:
  mysql:
  redis:


services:
  web:
    build:
      context: ./web
      dockerfile: ./Dockerfile
    container_name: wakty-web
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - server
    command: [ 'nginx-debug', '-g', 'daemon off;' ]
    networks:
      network:
        ipv4_address: 177.7.0.11

  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: wakty-server
    restart: always
    ports:
      - '8888:8888'
    depends_on:
      # - mysql
      - redis
    links:
      # - mysql
      - redis
    networks:
      network:
        ipv4_address: 177.7.0.12

  # mysql:
  #   image: mysql:8.0.21 # If you are a arm64 architecture: such as MacOS M1, please amend the mirror image: the mysql/mysql - server: 8.0.21
  #   container_name: gva-mysql
  #   command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #Set the utf8 character set
  #   restart: always
  #   ports:
  #     - "13306:3306" # Physical direct mapping host port for 13306
  #   environment:
  #     MYSQL_DATABASE: 'qmPlus' # Initialization is started to create the name of the database
  #     MYSQL_ROOT_PASSWORD: 'Aa@6447985' # The root administrator user password
  #   volumes:
  #     - mysql:/var/lib/mysql
  #   networks:
  #     network:
  #       ipv4_address: 177.7.0.13

  redis:
    image: redis:6.0.6
    container_name: gva-redis # Container name
    restart: always
    ports:
      - '16379:6379'
    volumes:
      - redis:/data
    networks:
      network:
        ipv4_address: 177.7.0.14
