package autocode

type ApiGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.
	AutoCodeExampleApi
	GatewaysApi
	CategoriesApi
	ProvidersApi
	VersionsApi
	TerminalsApi
	FieldsApi
	ServicesApi
	MerchantApi
	PackagesApi
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
