package autocode

type RouterGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.
	AutoCodeExampleRouter
	CategoriesRouter
	ProvidersRouter
	GatewaysRouter
	FieldsRouter
	PackagesRouter
	FrontendsRouter
	ServicesRouter
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
