package autocode

type RouterGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.
	AutoCodeExampleRouter
	GatewaysRouter
	CategoriesRouter
	ProvidersRouter
	VersionsRouter
	TerminalsRouter
	FieldsRouter
	ServicesRouter
	MerchantRouter
	PackagesRouter
	ServiceFieldsRouter

	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
